name: Final Workflow
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    
# Define the Jobs we want to run as part of this Workflow
jobs:
  # Define our build and test Job
   unit-test: 
    name: Unit tests
    # We want to run this Job on an Ubuntu VM 
    runs-on: ubuntu-latest
    steps:
     
      # Checkout the repository code using V1 of the standard checkout Action
      - uses: actions/checkout@v2
   
       # Use the standard Java Action to setup Java 
      - uses: actions/setup-java@v1
        with:
          # we want the latest Java 12
          java-version: '12.x'
         
     
        # Use the community Action to install Flutter
      - uses: subosito/flutter-action@v1
        with:
          # we want the stable channel
          channel: 'dev'  
  
        # Get flutter packages
      - run: flutter pub get
       # Analyze our Dart code
  # Check for any formatting issues in the code.
   # - run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
   # - run: flutter analyze .
    
    # Run widget tests for our flutter project.
      - run: flutter test
    
    # Build apk.
      - run: flutter build apk
    
    # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk


  
